# install.packages("shinyjs")
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)
library(shinyEffects)
library(shinyWidgets)
library(shinyjs)
library(bslib)
library(bsplus)
library(dplyr)
library(tibble)
library(sf)
library(units)
library(openxlsx)
library(igraph)
library(stringr)
library(stringi)
library(stars)
library(starsExtra)
library(leaflet)
library(leaflet.extras)
library(leafem)
library(dipsaus)
library(downlo)

options(shiny.maxRequestSize=150*1024^2)

source("./Modules/leer_sf.R")
source("./functions/Accordion_info.R")
source("./functions/st_order.R")
source("./functions/functions.R")

# comunas <- read_sf("n:/Dashboard PAS 150/COMUNAS/COMUNAS_v1.shp")
