install.packages("shinyjs")
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)
library(shinyEffects)
library(shinyWidgets)
library(shinyjs)
library(bslib)
library(bsplus)
library(dplyr)
library(tibble)
library(sf)
library(units)
library(openxlsx)

source("./Modules/leer_sf.R")
source("./functions/Accordion_info.R")